# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Moonstock' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Moonstock
  pod 'Stripe', '~> 14.0.0'

  target 'Moonstock-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MoonstockTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
